name: Bug Report
description: Use this template for reporting bugs
title: '[Bug]: '
labels: 'bug'
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What is the bug you encountered?
      placeholder: Provide a concise description of the bug
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of the software are you using?
      placeholder: Provide the version of the software
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: (Browser, OS, environment, etc.)
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Provide a concise description of the expected behavior
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened? Provide a description of the encountered behavior + steps to reproduce
      placeholder: |
        Behavior Description:

        Steps to Reproduce:
        1. Step 1
        2. Step 2
        3. Step 3
    validations:
      required: true
  - type: textarea
    id: relevant-code-or-logs
    attributes:
      label: Relevant Code or Logs
      description: Provide any relevant code or logs
      placeholder: |
        Relevant Code or Logs:
        ```
        // Your code here
        ```
    validations:
      required: false